"use client";

import { ColorModeScript } from "@chakra-ui/react";
import { Inter } from 'next/font/google';

import { Providers } from "./providers";

const inter = Inter({ subsets: ['latin'] });

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja" data-theme="light">
      <body className={inter.className}>
        <ColorModeScript type="cookie" nonce="testing" />
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
